[package]
name = "serverbackend"
version = "0.1.0"
authors = ["Chris2355"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
